import "petalFlower"
import "radialLeafFunction"
import 'onInteract'
import 'onTick'
import 'onPlace'
import 'customSapling'
import 'doublePlant'
import 'onPlayerDestroy'
import 'onPlayerPlaced'
import 'weaponEffects'
import 'toolDurability'
import 'fallingLeaves'
import 'armorEffects'
import 'blockMineSpeed'
import 'blockDurability'
import 'mapleLog'
import './Advancements/handler';